# Generated by Django 5.1.7 on 2025-05-01 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("calorie", models.FloatField(null=True)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "RICE"),
                            (2, "SOUP"),
                            (3, "MAIN_DISH"),
                            (4, "SIDE_DISH"),
                            (5, "DESSERT"),
                        ],
                        null=True,
                    ),
                ),
                ("nutrition", models.CharField(max_length=255, null=True)),
                ("allergy", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "food",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                (
                    "meal_type",
                    models.IntegerField(
                        choices=[(1, "Breakfast"), (2, "Lunch"), (3, "Dinner")],
                        null=True,
                    ),
                ),
                ("evaluation", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "menu",
            },
        ),
        migrations.CreateModel(
            name="FoodMenu",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "food",
                    models.ForeignKey(
                        db_column="food_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_appearances",
                        to="llmchatbot.food",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        db_column="menu_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="llmchatbot.menu",
                    ),
                ),
            ],
            options={
                "db_table": "food_menu",
            },
        ),
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField(null=True)),
                ("evaluation", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateField(null=True)),
                (
                    "food_menu",
                    models.ForeignKey(
                        db_column="food_menu_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="llmchatbot.foodmenu",
                    ),
                ),
            ],
            options={
                "db_table": "feed_back",
            },
        ),
    ]
